SELECT
    FOOD_PRODUCT.PRODUCT_ID,
    FOOD_PRODUCT.PRODUCT_NAME,
    SUM(FOOD_PRODUCT.PRICE*FOOD_ORDER.AMOUNT) AS TOTAL_SALES
FROM
    FOOD_ORDER
INNER JOIN
    FOOD_PRODUCT
ON
    FOOD_PRODUCT.PRODUCT_ID=FOOD_ORDER.PRODUCT_ID
WHERE
    FOOD_ORDER.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY
    1, 2
ORDER BY
    3 DESC,
    1