SELECT
    FIRST_HALF.FLAVOR
FROM
    ICECREAM_INFO
INNER JOIN
    FIRST_HALF
ON
    ICECREAM_INFO.FLAVOR=FIRST_HALF.FLAVOR
WHERE
    ICECREAM_INFO.INGREDIENT_TYPE='fruit_based'
GROUP BY
    1
HAVING
    SUM(FIRST_HALF.TOTAL_ORDER)>3000
ORDER BY
    SUM(FIRST_HALF.TOTAL_ORDER) DESC