WITH BEST_REVIEWER AS(
    SELECT
        REST_REVIEW.MEMBER_ID
    FROM
        REST_REVIEW
    INNER JOIN
        MEMBER_PROFILE
    ON
        REST_REVIEW.MEMBER_ID=MEMBER_PROFILE.MEMBER_ID
    GROUP BY
        1
    ORDER BY
        COUNT(*) DESC
    LIMIT 1
)
SELECT
    MEMBER_PROFILE.MEMBER_NAME,
    REST_REVIEW.REVIEW_TEXT,
    DATE_FORMAT(REST_REVIEW.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM
    REST_REVIEW
INNER JOIN
    MEMBER_PROFILE
ON
    REST_REVIEW.MEMBER_ID IN (SELECT MEMBER_ID FROM BEST_REVIEWER)
    AND REST_REVIEW.MEMBER_ID=MEMBER_PROFILE.MEMBER_ID
ORDER BY
    3, 2