SELECT
     PRODUCT.PRODUCT_CODE,
     SUM(OFFLINE_SALE.SALES_AMOUNT*PRODUCT.PRICE) AS SALES
FROM
    OFFLINE_SALE
INNER JOIN
    PRODUCT
ON
    PRODUCT.PRODUCT_ID=OFFLINE_SALE.PRODUCT_ID
GROUP BY
    1
ORDER BY
    2 DESC, 1