WITH FOOD_RN AS(
SELECT
    CATEGORY,
    PRODUCT_NAME,
    PRICE,
    ROW_NUMBER() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RN
FROM
    FOOD_PRODUCT
WHERE
    CATEGORY IN ('과자', '국', '김치', '식용유')
)
SELECT
    CATEGORY,
    PRICE AS MAX_PRICE,
    PRODUCT_NAME
FROM
    FOOD_RN
WHERE
    RN=1
ORDER BY
    2 DESC