WITH JOIN_TABLE AS(
    SELECT
        AUTHOR.AUTHOR_ID,
        AUTHOR.AUTHOR_NAME,
        BOOK.CATEGORY,
        BOOK_SALES.SALES_DATE,
        BOOK.PRICE*BOOK_SALES.SALES AS SALES_PRICE
    FROM
        BOOK_SALES
    INNER JOIN
        BOOK
    ON
        BOOK_SALES.BOOK_ID=BOOK.BOOK_ID
    INNER JOIN
        AUTHOR
    ON
        AUTHOR.AUTHOR_ID=BOOK.AUTHOR_ID
)
SELECT
    AUTHOR_ID,
    AUTHOR_NAME,
    CATEGORY,
    SUM(SALES_PRICE) AS TOTAL_SALES
FROM
    JOIN_TABLE
WHERE
    SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY
    1, 2, 3
ORDER BY
    1, 3 DESC