WITH JOIN_TABLE AS(
    SELECT
        BOOK.CATEGORY,
        SALES
    FROM
        BOOK_SALES
    INNER JOIN
        BOOK
    ON
        BOOK_SALES.BOOK_ID=BOOK.BOOK_ID
    WHERE
        BOOK_SALES.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
)
SELECT
    CATEGORY,
    SUM(SALES) AS TOTAL_SALES
FROM
    JOIN_TABLE
GROUP BY
    1
ORDER BY
    1