WITH CAR_IDS AS(
    SELECT
        DISTINCT CAR.CAR_ID
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY  AS RENTAL_HISTORY
    INNER JOIN
        CAR_RENTAL_COMPANY_CAR AS CAR
    ON
        CAR.CAR_ID=RENTAL_HISTORY.CAR_ID
        AND CAR.CAR_TYPE IN ('세단', 'SUV')
    WHERE (
        START_DATE BETWEEN '2022-11-01' AND '2022-11-30'
        AND END_DATE BETWEEN '2022-11-01' AND '2022-11-30'
    ) OR (
        '2022-11-01'  BETWEEN START_DATE AND END_DATE
        OR '2022-11-30' BETWEEN START_DATE AND END_DATE
    )
)
SELECT
    CAR.CAR_ID,
    CAR.CAR_TYPE,
    CAST((100-DISCOUNT_PLAN.DISCOUNT_RATE)/100*CAR.DAILY_FEE*30 AS signed) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR  AS CAR
LEFT JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DISCOUNT_PLAN
ON
    CAR.CAR_TYPE=DISCOUNT_PLAN.CAR_TYPE
    AND DISCOUNT_PLAN.CAR_TYPE IN ('SUV', '세단')
WHERE
    CAR.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_IDS)
    AND DISCOUNT_PLAN.DURATION_TYPE='30일 이상'
    AND (100-DISCOUNT_PLAN.DISCOUNT_RATE)/100*CAR.DAILY_FEE*30>=500000
    AND (100-DISCOUNT_PLAN.DISCOUNT_RATE)/100*CAR.DAILY_FEE*30<2000000
ORDER BY
    3 DESC,
    2,
    1 DESC
