-- https://school.programmers.co.kr/learn/courses/30/lessons/59412
-- 입양 시각 구하기(1)
-- GROUP BY

SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT FROM ANIMAL_OUTS GROUP BY HOUR(DATETIME) HAVING HOUR>=9 AND HOUR<20 ORDER BY HOUR(DATETIME)