-- https://school.programmers.co.kr/learn/courses/30/lessons/59044?language=mysql
-- 오랜 기간 보호한 동물(1)
-- JOIN

SELECT AI.NAME, AI.DATETIME FROM ANIMAL_INS AS AI LEFT JOIN ANIMAL_OUTS AS AO ON AO.ANIMAL_ID=AI.ANIMAL_ID WHERE AO.ANIMAL_ID IS NULL ORDER BY AI.DATETIME LIMIT 3