-- https://school.programmers.co.kr/learn/courses/30/lessons/59043
-- 있었는데요 없었습니다
-- JOIN

SELECT AO.ANIMAL_ID, AO.NAME FROM ANIMAL_OUTS AS AO JOIN ANIMAL_INS AS AI ON AI.ANIMAL_ID=AO.ANIMAL_ID WHERE AI.DATETIME>AO.DATETIME ORDER BY AI.DATETIME